#!/bin/bash
#
# Generation script the level image tile sheet.
#
# All the single .png files in /tiles are montaged together onto a big image sheet, 
# 8 in a row, 101x171 pixels (size determined by tile image library 
# ( http://www.lostgarden.com/2007/05/dancs-miraculously-flexible-game.html )
#
# This script also updates the blocks.js constants and the java Block enum to have 
# the current state of blocks be reflected in both the client-side js world and
# server Java world.
#


cd $(dirname $0)

montage $(ls tiles/*.png) -geometry 101x171+0+0 -tile 8x8 -background transparent ../src/main/webapp/image/sheet.png

cd tiles
cnt=-1

java_file="../../src/main/java/org/boom/level/Block.java"
js_file="../../src/main/webapp/script/blocks.js"
 
echo -ne "package org.boom.level;\n\n/** Enum for level tile types. Do not edit, auto-generated by create-sheet.sh */\npublic enum Block {" > $java_file
echo "// Tile constants. Do not edit, auto-generated by create-sheet.sh" > $js_file

for i in *.png; do 

	cnt=$(($cnt + 1))
	name="$(echo $i | tr "[:lower:]" "[:upper:]" | sed -e "s/\.PNG//g" -e "s/0/EMPTY/" )"
	
	echo "var BLOCK_$name = $cnt;" >> $js_file
	if [[ $cnt = "0" ]]; then
		echo -ne "\n    " >> $java_file
	else
		echo -ne ", " >> $java_file
	fi
	echo -n "$name" >> $java_file
	
done
echo -e "\n}" >> $java_file

